CBCTemplate = {
                'headers' : {'CATEGORY' : 1, 
                            'NAME' : 1, 
                            'DESCRIPTION' : 1, 
                            'MANUFACTURER' : 1,
                            'MODEL' : 1,
                            'VENDOR' : 1, 
                            'ITEM URL' : 1, 
                            'COUNT (#)' : 1,
                            'LENGTH (FT)' : 1,
                            'LENGTH (MM)' : 1,
                            'WIDTH (FT)' : 1,
                            'WIDTH (MM)' : 1,
                            'HEIGHT (FT)' : 1,
                            'HEIGHT (MM)' : 1,
                            'AREA (SQF)' : 1,
                            'AREA (SQM)' : 1,
                            'UNIT' : 1,
                            'UNIT COST ($)' : 1,                         
                            'ADDITIONAL COST ($)' : 0, 
                            'ADDITIONAL COUNT (#)' : 0, 
                            'SHIPPING ($)' : 0, 
                            'OTHER COSTS ($)' : 0, 
                            'DESCRIPTION OF OTHER COSTS' : 0,
                            # 'TOTAL COUNT (per row, based on specified UNIT)' : 0,
                            'TOTAL COST ($)' : 0, 
                            'CURRENCY' : 0,
                            'TOTAL ($) USD' : 0,
                            'SUBSCRIPTION' : 0, 
                            'SKU #' : 0, 
                            'COLOR' : 0, 
                            'ORDER STATUS' : 0, 
                            'SHIPPER' : 0, 
                            'TRACKING URL' : 0, 
                            'TRACKING #' : 0, 
                            'STORAGE LOCATION' : 0, 
                            'SETUP STATUS' : 0, 
                            'INSTALLATION TYPE' : 0, 
                            'INSTALLER' : 0, 
                            'NOTES' : 0, 
                            'IMAGE 1' : 1, 
                            'IMAGE 2' : 1, 
                            'IMAGE 3' : 1, 
                            'IMAGE 4' : 1, 
                            'IMAGE 5' : 1, 
                            'IMAGE 6' : 1, 
                            'IMAGE 7' : 1, 
                            'IMAGE 8' : 1, 
                            'IMAGE 9' : 1,
                            'UniqueID (DO NOT REMOVE COLUMN)' : 1},

                # List of words to not be capitalized or lower-cased
                'acronyms' : ['FT',
                              'MM',
                              'M',
                              'KM',
                              'INCH',
                              'SQF',
                              'SQM',
                              'URL',
                              'CAD',
                              'USD',
                              'UniqueID']
}